### ISSUE TITLE
Plot enhancements

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/quickPlot#1]
Various; copied from https://github.com/PredictiveEcology/SpaDES/issues/187

- [x] Allow plotting of a simList object
- [x] Allow custom titles for each plot fa5d6c75b4253bdf4a9a8c798ba4f8751bbe30f2 
- [ ] Allow legend title, like "units" (Yong) (#186)
- [x] Allow rearranging of device with a manual resize of device, likely at each new call to Plot
- [x] Make error messages more meaningful when passing wrong objects, which will solve #160
- [x] axes needs to be part of spadesPlot 
- [x] Make error messages more meaningful when passing wrong objects (part of #183)
- [x] allow other "..." arguments to pass to plotting, formerly #154, 
- [x] igraph, hist, base added to .spadesPlot , formerly #154 49ff508d0c435a6f4335580be5050fcf2315fd1e 0442418675e508e8b7c679c38a07024573e3c4ea 
- [ ] #113 speedupScale in polygons needs optimizing for all cases
- [ ] #119 raster pixels are not square - not Plotting correctly
- [x] na.color and zero.color don't override if the lowest value is negative (see map differences in SpaDESUI)
- [x] #221 Update Plot to allow legends to be updated  
- [x] Allow negative value rasters to be plotted
- [x] Allow single value rasters whose value is not "pretty" e1f239b9f2e6adb0764467a091baf6539fec5479
- [x] Allow factor rasters that are missing values "at their ends"... like a raster that only has 3, but the levels go from 1 to 4 834a7c27e3293d71ea5326ea5e34750fcf3e8b55
- [ ] Create abstraction for making `.plotGrob` methods that can be created by a user for new classes. Likely rename .plotGrob to be a user function and export it.
- [x] Allow user supplied arrangements 547041ff7edabc05ae5a968801e735d471c0d3c9 
- [x] Allow individual plots to be wiped with new = TRUE, instead of whole device (use clearPlot for that) 296b51b6289c26524e885c8293e013bd75b92e5a

**Comment by achubaty** [comment]
@eliotmcintire can you please review to see how many of these are still outstanding, and close if resolved?

**Comment by eliotmcintire** [comment]
Some of these are very low priority. I would prefer closing this issue for these remaining, as they will likely never be done. The MUCH larger issues, i.e., plotting `terra` and `sf` classes was done.
